### ISSUE TITLE
Ledger-app-trtl freeze when open on nano s

### ISSUE THREAD

**Issue by rosescu** [turtlecoin/ledger-app-turtlecoin#2]
https://photos.app.goo.gl/gF6EbEydgwzdjmNA8
https://photos.app.goo.gl/LUGfzozqRLQ77WDp8
Wallet: turtle-wallet-proton-3.4.9 
Issue: nano s side: when open the ledger-app-turtlecoin the screen freeze on "Open application". device must be unplugged.
           wallet side: after login nano s and before opening ledger-app, the message is "Please Confirm Prompt on your Ledger" and after opening the ledger-app the nano s screen freeze on "Open Aplication" and wallet send "Ledger detect error! No ledger was detected. Make sure you have a ledger plugged in"

**Comment by brandonlehmann** [comment]
This may be an issue with the app running on the latest ledger firmware and/or building with the latest SDK. This ledger application is slated for an entire rebuild for v2 so additional work won’t be completed on this copy.
